### ISSUE TITLE
timestamp is way off, hour jumps back and forth

### ISSUE THREAD

**Issue by gigawatts** [cbdevnet/ipmagnet#16]
The timestamp reported on your website is way off. I assume it is supposed to be reporting the same timezone my browser's local clock is set to?

For example, I just loaded the page at 19:55 local time. The last update, which I know was within the last minute of loading the page (because I clicked the clear my data button, and forced a tracker update on my torrent client), first reports "30.01.2020 **20**:17:13", then about 10 seconds later, the same line changes and reports "30.01.2020 **19**:17:13".

Every time the page is manually refreshed, the hour reports 20, then flips back to 19 ten seconds later.

Edit: I should probably note, this is experienced on the http://ipmagnet.services.cbcdn.com/ site, not something I am self-hosting.

**Comment by cbdevnet** [comment]
Hi, thanks for reporting this! I'll look into it :)

**Comment by cbdevnet** [comment]
OK this seems to be a problem when switching between the pure-HTML (non-javascript) view and the javascript-enabled view.

The page is first loaded from the server with all dates rendered in the timezone set on the server (by the [code in index.php](https://github.com/cbdevnet/ipmagnet/blob/master/index.php#L167)).
Once all resources have loaded on the client, the browser calls the `init()` function, which (if sucessful) upgrades the view to the JavaScript-enabled interfaces and, in the process, renders all timestamps in the timezone of the browser (see https://github.com/cbdevnet/ipmagnet/blob/master/static/ipmagnet.js#L115).

Since there is no easy way to get the clients' timezone from the initial HTTP request, the only solutions I can currently think of would be to either

* Force all timestamps to display in a common timezone (e.g. UTC)
* Explicitly add the timezone identifier so the jumps are at least explainable

Do you have any preference or other ideas?

**Comment by gigawatts** [comment]
My initial thought is display the Timezone tag all the time, use UTC if JS is disabled, and switch to local browser TZ if/when it can be read from the client. 

One step further might be to add a toggle that allows you to switch between local TZ and UTC when JS is enabled.

The other issue seems to be the minutes are way off, something like 40 minutes behind (if indeed the post init() time displayed is my local TZ)

**Comment by cbdevnet** [comment]
The weird offset might just be because I don't really keep the server time synchronized to anything ;D

**Comment by gigawatts** [comment]
I'm guessing you just synced it, spot on now!

**Comment by cbdevnet** [comment]
Yup :) I'll add the timezone indicator in the next few days :)

**Comment by cbdevnet** [comment]
All dates should now show timezones (you may have to refresh your browser cache to see it in the version hosted at http://ipmagnet.services.cbcdn.com/).

I thought about making the displayed timezone configurable, but decided against it primarily to keep the source code simple and readable even to people who do not have a strong programming background. Since this is a privacy (enhancement) tool, I feel it is important that everyone considering hosting this tool for him/herself has the chance to verify what exactly the code does.

**Comment by gigawatts** [comment]
Cool! Confirmed the update works. Makes much more sense now what time is actually being displayed. It's still a little "jarring" to see the hours/timezone change when you are not expecting it, but at least now I understand why it's doing so.

Thanks for the really fast response and fix, and thanks for creating an awesome tool. It's great for troubleshooting, and it's also great as a sort of DDNS system, to track IP changes on remote managed hosts.

**Comment by gigawatts** [comment]
FYI, looks like your clock is running about 20 minutes slow again :clock2:

**Comment by cbdevnet** [comment]
Synced it again, thanks :)
